### ISSUE TITLE
Error: Failed to load config "airbnb" to extend from.

### ISSUE THREAD

**Issue by jhohlfeld** [ijsto/eslint-config-nextjs#2]
Got this error in VSCode:
> Error: Failed to load config "airbnb" to extend from.

I followed your install steps, so maybe your docs are not complete?

**Comment by jhohlfeld** [comment]
All good. I was installing with yarn. I didn't know that yarn seems incapable of handling peer dependencies (at least I didn't' t find a simple solution).

**Comment by ScottAgirs** [comment]
@jhohlfeld thanks for posting your solution. Yarn and npm sometimes do handle things differently... I will look into this and try to enable both
