### ISSUE TITLE
CRA issue

### ISSUE THREAD

**Issue by MariuzM** [ijsto/eslint-config-nextjs#3]
It's working fine one my Next.js app but when i tried on CRA I'm getting this error

![Screenshot 2020-05-08 at 19 55 05](https://user-images.githubusercontent.com/36937039/81439175-de912500-9165-11ea-9754-ce99f7105cae.png)
![Screenshot 2020-05-08 at 19 54 57](https://user-images.githubusercontent.com/36937039/81439195-e5b83300-9165-11ea-9c6c-1f18e8b0df15.png)

**Comment by ScottAgirs** [comment]
hey @MariuzM, thanks for reporting this, feel free to describe in a bit more detail what is the exact issue? Otherwise, I've tried reproducing on CRA and on Next.js, seems to be working fine.

**Please note:** this config assumes semicolons at the end of the appropriate lines.

**Comment by MariuzM** [comment]
Sorry guys I'm an idiot forgot to add .prettierrc.js to CRA
