### ISSUE TITLE
support TypeScript?

### ISSUE THREAD

**Issue by MariuzM** [ijsto/eslint-config-nextjs#4]
Apologies for noob question but i assume this does not support TS, I've tried it with Next.js + TS and nothing.

**Comment by ScottAgirs** [comment]
hey @MariuzM totally fine! We don't have any docs on this yet, so it's a legit question! :) 

Currently, we don't support TSLint out of the box with this package, but with the official launch of iJS later this month/early June, a quick guide on how to set up ESLint with TS is coming soon for our [eslint-config](https://www.npmjs.com/package/@ijsto/eslint-config) package, will definitely post something about it on social media, so feel free to follow there 🎉  

I will close this for now but feel free to re-open if you have any more questions
